### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [semwai/Haffman#1]
1. https://github.com/semwai/Haffman/blob/89f904f50835efd65174e17e68bbc9d5eaec026c/app/src/main/java/com/semwai/huffman/MainActivity.kt#L21 Тут лучше сразу сделать `shuffled` и взять нужное число символов с помощью `take`, не делая `toMutableList`, а потом просто перебирать элементы полученного списка в `for`.
1. Использовать перемешанный список чисел для генерации частоты появления символов не имеет смысла, ведь Вы не требуете неповторяющихся чисел, так что можно просто генерировать случайное число в диапазоне.
1. Перевод из `myMap` в список кнопок следует вынести в функцию, ведь Вы делаете это два раза:при генерации и при ручном добавлении.
1. По поводу передачи `Map` в activity не могу однозначно сказать, как было бы лучше сделать. Мне кажется, что было бы неплохо, если бы Вы сделали класс, реализующий `Parcelable`, для сохранения `Map` в intent. А ещё, не знаю как сейчас, но когда я последний раз разбирался с Android (примерно год назад) было модно делать приложения из одной activity, а вместо разных activity использовать фрагменты. В таком случае нет проблемы передачи объектов между activity.
1. https://github.com/semwai/Haffman/blob/89f904f50835efd65174e17e68bbc9d5eaec026c/app/src/main/java/com/semwai/huffman/Huffman.kt#L10 Вот это очень плохо. Используйте какой-нибудь настоящий тип вместо `Any`, например, `List<Char>` или `String`. Тогда Вы, кстати, заметите, что для большой вложенности у Вас получаются очень интересные конструкции из List<List<List<List<List<Char>>>>> и т.п.(он и `toString` возвращает не такой, как Вы хотите).
1. Кстати, `getWeight()` и `getChars()` можно делать не методами, а полями (точнее, свойствами) ведь их можно вычислить один раз.
1. В конструктор `Huffman` лучше передавать не строку, а готовый `Map`. `Huffman` никак не относится к activity, поэтому незачем затаскивать сюда костыль для передачи `Map`. В крайнем случае, можно сделать для этих целей вспомогательную функцию.
1. В текущей реализации `inputNodes` можно сделать локальной переменной в конструкторе. Но лучше бы воспользоваться этим уже готовым деревом, а не разбивать заново при отрисовке по первым символам строк. И в таком случае хранить лучше не список из одного корневого элемента, а просто корневой элемент.
1. https://github.com/semwai/Haffman/blob/89f904f50835efd65174e17e68bbc9d5eaec026c/app/src/main/java/com/semwai/huffman/Huffman.kt#L34 Тут не обязательно создавать копию, достаточно явно указать тип возвращаемого значения.
1. https://github.com/semwai/Haffman/blob/89f904f50835efd65174e17e68bbc9d5eaec026c/app/src/main/java/com/semwai/huffman/Huffman.kt#L40-L45 Понятно, что здесь количество элементов не очень велико, поэтому производительность здесь не принципиально. Но если бы она была важна (для большого числа элементов), то для такого алгоритма следует использовать `PriorityQueue`, чтобы не сортировать весь массив заново каждый раз.
1. https://github.com/semwai/Haffman/blob/89f904f50835efd65174e17e68bbc9d5eaec026c/app/src/main/java/com/semwai/huffman/Huffman.kt#L55-L57 Если используете `with`, то внутри нужно использовать не `po`, а `this`(то есть просто обращаться к `a` и `b`).
1. Возвращаемое значение метода `make` нигде не используется.
1. При отрисовке элементы начинают перекрывать друг на друга, начиная с 6 ряда.
1. `tapCount` вполне можно сделать `Boolean` и переименовать.
1. https://github.com/semwai/Haffman/blob/89f904f50835efd65174e17e68bbc9d5eaec026c/app/src/main/java/com/semwai/huffman/Drawer.kt#L168-L169 У Вас очень криво работает перемещение дерева и баг в этих строчках. Подозреваю, что множитель 10 у Вас появился как попытка скомпенсировать слишком быстрое перемещение. А проблема на самом деле в том, что `dX` и `dY` - это у Вас смещение пальца от начала перемещения (`ACTION_DOWN`), а не от прошлой обработки перемещения (`ACTION_MOVE`). Так что если, например, во время перемещения пальца обработка будет вызвана 3 раза через каждые 5 пикселей, то вместо смещения дерева на 15 пикселей, Вы сместите его на 5+10+15=30 пикселей, и дальше расхождение будет ещё больше.
1. Не помешало бы добавить тестов, хотя бы для `Huffman`.

**Comment by semwai** [comment]
1. Переделал генерацию. Теперь беру просто алфавит и добавляю побуквенно вместе с рандомным числом. Для наглядности сойдет.
2. Исправил.
3. Сделал `letterButton(i: Char, c: Int): Button`
4. Решил оставить activity как есть. Тип `linkedMapOf` можно передавать в интент, т.к. там реализован перевод в `Serializable`
5. Сделал `fun getChars(): String`
6. Исправил.
7. Сделал `class Huffman(input: Map<Char, Int>)`
8. Принципиально переделал способ отрисовки дерева. 

- Отрисовка работает с готовым экземпляром `Huffman.HNode`
- Оптимизировал графическое представление дерева путем расчета ширины и высоты сдвига для каждого элемента. Реализовано в отдельной функции `fun offsetMaster(inputGraph: Huffman.HNode): Map<String,  Pair<Float,Float>>` . Решил не добавлять ее в класс Huffman, т.к. она скорее относится к графическому представлению и является необходимым только для представления. 
9. Исправил 
10. Исправил
11. Исправил
12. Исправил.
13. См п.8. Иногда все-таки отрисовка может быть не идеальной, но может я еще поиграюсь с коэффициентами и прочим. Примерно в каждом 6-м графе на 26 элементом появляются маленькие коллизии, но чаще всего они не существенны. 
14. Исправил.
15. Исправил. Теперь еще можно приближать граф двумя пальцами. 
16. Тест добавил. `app\src\test\java\com\semwai\huffman`

В [Google Play](https://play.google.com/store/apps/details?id=com.semwai.haffman) должно обновится в ближайшее время.

**Comment by maximpetrov** [comment]
1. По пункту 3. Я предлагал вынести в метод весь процесс по перезаполнению списка: очистка списка + цикл по `myMap`, но так тоже сгодится.
1. По пункту 8. Всё-таки сделайте `inputNodes` локальной переменной в `init`, а вместо `getRootNode` сделайте поле, в которое в конце `init` положите `inputNodes.first()`.
1. По пункту 10. Вместо `first` + `remove` лучше использовать `poll`, как штатный (а, значит, точно самый эффективный) способ получить очередной элемент из очереди.
1. По пункту 15, а точнее по масштабированию. Во-первых, почему Вы не домножаете смещение совсем, если `scale` вышел за рамки, хотя сам `scale` при этом доводите до этих рамок. То есть, если `scale` был 3, а `scaleFactor` был 1.5, то Вы увеличите `scale` до 4, а смещение не изменится. Во-вторых, идеально было бы подправить это масштабирование, чтобы дерево не уезжало в сторону. Тут проблема в том, что смещение, которое Вы пропорционально увеличиваете - это фактически смещение верхнего левого угла экрана. То есть Вы фиксируете именно верхний левый угол, а хорошо бы зафиксировать точку, в которой масштабируете.
1. По пункту 16. Тесты ну очень простые, сделайте хотя бы дерево побольше.

**Comment by semwai** [comment]
Я исправил. Особенно больно мне дался мультитач, я с ним разобрался, но правда иногда бывает в некоторых случаях поддергивания после быстрого скейлинга. Со смещением я разобрался, но не совсем как вы говорили. А может вы это и имели в виду и я не понял изначально :D
`xOffset = xOffset * detector.scaleFactor`
поменял на
`xOffset = xOffset * detector.scaleFactor + detector.focusX * (detector.scaleFactor - 1)`

**Comment by maximpetrov** [comment]
По поводу смещения я имел в виду ровно это, так что всё хорошо. А вот с мультитачем не очень красивый костыль у Вас получился со `sleep(50)`, который работает к тому же только если быстро убрать пальцы после масштабирования. А если вообще не масштабировать, а просто начать двигать двумя пальцами (параллельно, чтобы масштабирование не получилось), а потом отпустить первый палец, то этот баг проявится во всей красе. Проблема в том, Вы запоминаете точку касания вторым пальцем, а потом он сдвигается, но Вы это не записываете, поэтому при отрыве первого пальца картинка прыгает на это смещение. Исправить это можно очень просто: в конце `onTouchEvent` следует обновлять `startX` и `startY` для всех активных пальцев (циклом от 0 до `event.pointerCount`) причем независимо от `isScaleProcess`. А в `when` можно оставить только обработку `ACTION_MOVE`, причём `actionIndex` Вам не нужен, так как он работает только для `ACTION_POINTER_UP` и `ACTION_POINTER_DOWN`, а в остальных случаях он равен 0 (0 Вас устраивает в этом случае).

**Comment by semwai** [comment]
Надеюсь 
`
 for (i in 0 until event.pointerCount) {
   startX[i] = event.getX(i)
   startY[i] = event.getY(i)
   }
`

А еще если добавлять в название коммита ссылку на issue, то он закрывается автоматически при пуше на сервер гита (по крайней мере я не специально закрывал)

**Comment by maximpetrov** [comment]
https://github.com/semwai/Haffman/blob/0549b6500d31f9941e43aec12be4472ac07151b6/app/src/main/java/com/semwai/huffman/ScaleCanvas.kt#L34-L35 Это теперь лишнее, Вы же всё равно в конце все пальцы сохраняете.
https://github.com/semwai/Haffman/blob/0549b6500d31f9941e43aec12be4472ac07151b6/app/src/main/java/com/semwai/huffman/ScaleCanvas.kt#L38-L41 А тут Вы забыли для каждого пальца найти id, ведь именно id у Вас является ключом.

**Comment by semwai** [comment]
Спасибо, исправил.

**Comment by maximpetrov** [comment]
Принято
